version: '3.5'
services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - ${VIRTUAL_PORT}:80
    restart: always
    depends_on:
      - wordpress
    env_file: .env
    volumes:
      - data-wp:/var/www/html:ro
      - ./setting/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./setting/nginx/conf:/etc/nginx/conf/:ro
      - ${THEME_DIRECTORY}:/var/www/html/wp-content/themes/:ro
    networks:
      - front
      - back

  wordpress:
    build: ./docker/wordpress
    ports:
      - 9000:9000
    restart: always
    env_file: .env
    depends_on:
      - mysql
    volumes:
      - data-wp:/var/www/html:rw
      - ./setting/php:/usr/local/etc/php:ro
      - ${THEME_DIRECTORY}${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}:ro
      - ${THEME_DIRECTORY}${CHILD_THEME_NAME}:/var/www/html/wp-content/themes/${CHILD_THEME_NAME}:ro
    networks:
      - back

  wpcli:
    image: wordpress:cli
    depends_on:
      - wordpress
      - mysql
    volumes:
      - data-wp:/var/www/html:rw
    links:
      - mysql
    networks:
      - back

  mysql:
    image: mysql:5.7
    ports:
      - 3333:3306
    restart: always
    env_file: .env
    environment:
        - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
        - MYSQL_USER=${WORDPRESS_DB_USER}
        - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql:rw
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    links:
      - mysql
    ports:
      - 8888:80
    volumes:
      - ./phpmyadmin/sessions:/sessions:rw
    networks:
      - back

volumes:
  data-wp:
    name: ${COMPOSE_PROJECT_NAME}-wp
  data-db:
    name: ${COMPOSE_PROJECT_NAME}-db

networks:
  front:
    external: true
  back:
