version: '3'
services:
  nginx:
    image: nginx:1.16.0-alpine
    ports:
      - ${VIRTUAL_PORT}:80
    restart: always
    depends_on:
      - wordpress
    env_file: .env
    volumes:
      - data-wp:/var/www/html:ro
      - ./setting/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./setting/nginx/conf:/etc/nginx/conf/:ro
      - ${THEME_DIRECTORY}:/var/www/html/wp-content/themes/${THEME_NAME}:ro
    networks:
      - front
      - back

  wordpress:
    build: ./docker/wordpress
    ports:
      - 9000:9000
    restart: always
    env_file: .env
    depends_on:
      - mysql
    volumes:
      - data-wp:/var/www/html:rw
      - ./setting/php:/usr/local/etc/php:ro
      - ${THEME_DIRECTORY}:/var/www/html/wp-content/themes/${THEME_NAME}:ro
    networks:
      - back

  mysql:
    image: mysql:5.7.22
    ports:
      - 3333:3306
    restart: always
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql
    networks:
      - back

volumes:
  data-wp:
    external:
      name: ${COMPOSE_PROJECT_NAME}-wp
  data-db:
    external:
      name: ${COMPOSE_PROJECT_NAME}-db

networks:
  front:
    external: true
  back: